module.exports.SystemTools=require('./lib/tools/SystemTools.js');
module.exports.HttpRequester=require('./lib/tools/HttpRequester.js');
module.exports.LauncherCore=require('./lib/core/LauncherCore.js');
module.exports.OfflineAuthenticator=require('./lib/authentication/OfflineAuthenticator.js');
module.exports.Yggdrasil=require('./lib/authentication/Yggdrasil.js');
module.exports.Downloader={
    Mojang:require('./lib/downloader/Mojang.js')
};
module.exports.Installer={
    Forge:require('./lib/tools/ForgeInstaller.js')
};